apiVersion: apps/v1
kind: Deployment

metadata:
  name: payment-service

spec:
  replicas: 1

  selector:
    matchLabels:
      app: payment-service

  template:
    metadata:
      labels:
        app: payment-service

    spec:
      containers:
        - name: payment-service
          image: payment-service:1.2
          imagePullPolicy: Never

          ports:
            - containerPort: 8082

          env:
            - name: SPRING_DATASOURCE_URL
              value: jdbc:mysql://payment-db:3306/payment

            - name: SPRING_DATASOURCE_USERNAME
              value: root

            - name: SPRING_DATASOURCE_PASSWORD
              value: root

            - name: SPRING_DATA_REDIS_HOST
              value: redis